parser: babel-eslint
extends: [airbnb, eslint:recommended]
rules: 
  no-plusplus: 2
  no-underscore-dangle: 2
  no-unused-vars: 1
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 1
  react/no-array-index-key: 1
  react/prefer-stateless-function: 0
  react/jsx-filename-extension: 0
  react/forbid-prop-types: 0
  react/no-unused-prop-types: 1
  react/destructuring-assignment: 1
  react/no-multi-comp: 1
env:
  browser: true
  jest: true
  commonjs: true